package es.uma.informatica.sii.trazabilidad.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pruebaInicio() {
    driver.get("http://0.0.0.0:8080/proyecto-war/faces/inicio.xhtml;jsessionid=dicIECg4s-F9sQtlK6jG82r5HUypx0A4NF74l5jM.711d50a7259c");
    driver.manage().window().setSize(new Dimension(891, 749));
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Identificarse"));
    driver.findElement(By.name("j_idt7:j_idt9")).click();
    driver.findElement(By.name("j_idt7:j_idt11")).click();
  }
  @Test
  public void pruebaalumnos() {
    driver.get("http://0.0.0.0:8080/proyecto-war/faces/inicio.xhtml");
    driver.manage().window().setSize(new Dimension(891, 749));
    driver.findElement(By.name("j_idt7:j_idt11")).click();
    driver.findElement(By.name("j_idt7:j_idt11")).click();
    driver.findElement(By.name("j_idt7:j_idt8")).click();
    driver.findElement(By.name("j_idt7:j_idt10")).click();
    driver.findElement(By.name("j_idt7:j_idt10")).sendKeys("12345678A");
    driver.findElement(By.name("j_idt7:j_idt12")).click();
    driver.findElement(By.name("j_idt7:j_idt12")).sendKeys("Pepe Garcia Garcia");
    driver.findElement(By.name("j_idt7:j_idt14")).click();
    driver.findElement(By.name("j_idt7:j_idt14")).sendKeys("pepe@uma");
    driver.findElement(By.name("j_idt7:j_idt16")).click();
    driver.findElement(By.name("j_idt7:j_idt16")).sendKeys("pepe@uma");
    driver.findElement(By.name("j_idt7:j_idt18")).click();
    driver.findElement(By.name("j_idt7:j_idt18")).sendKeys("123456789");
    driver.findElement(By.name("j_idt7:j_idt20")).click();
    driver.findElement(By.name("j_idt7:j_idt20")).sendKeys("987654321");
    driver.findElement(By.name("j_idt7:j_idt27")).click();
    driver.findElement(By.name("j_idt7:j_idt29")).click();
    driver.findElement(By.name("j_idt7:j_idt28")).click();
  }
  @Test
  public void pruebagrupos() {
    driver.get("http://0.0.0.0:8080/proyecto-war/faces/inicio.xhtml");
    driver.manage().window().setSize(new Dimension(891, 749));
    driver.findElement(By.name("j_idt7:j_idt11")).click();
    driver.findElement(By.name("j_idt7:j_idt10")).click();
    driver.findElement(By.name("j_idt7:j_idt12")).click();
    driver.findElement(By.name("j_idt7:j_idt12")).sendKeys("Calculo");
    driver.findElement(By.name("j_idt7:j_idt14")).sendKeys("1");
    driver.findElement(By.name("j_idt7:j_idt16")).sendKeys("A");
    driver.findElement(By.name("j_idt7:j_idt18")).click();
    driver.findElement(By.name("j_idt7:j_idt24")).sendKeys("1");
    driver.findElement(By.name("j_idt7:j_idt26")).sendKeys("A");
    driver.findElement(By.name("j_idt7:j_idt28")).sendKeys("Mañana");
    driver.findElement(By.name("j_idt7:j_idt30")).click();
    driver.findElement(By.name("j_idt7:j_idt38")).click();
  }
  @Test
  public void pruebavistasecretaria() {
    driver.get("http://0.0.0.0:8080/proyecto-war/faces/inicio.xhtml;jsessionid=dicIECg4s-F9sQtlK6jG82r5HUypx0A4NF74l5jM.711d50a7259c");
    driver.manage().window().setSize(new Dimension(891, 749));
    driver.findElement(By.name("j_idt7:j_idt11")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Secretaría: Asignación de Grupos"));
    driver.findElement(By.name("j_idt7:j_idt10")).click();
    driver.findElement(By.name("j_idt7:j_idt11")).click();
    driver.findElement(By.name("j_idt7:j_idt12")).click();
    driver.findElement(By.name("j_idt7:j_idt13")).click();
    {
      String value = driver.findElement(By.name("j_idt7:j_idt10")).getAttribute("value");
      assertThat(value, is("GRUPOS"));
    }
    {
      String value = driver.findElement(By.name("j_idt7:j_idt11")).getAttribute("value");
      assertThat(value, is("ALUMNOS"));
    }
    {
      String value = driver.findElement(By.name("j_idt7:j_idt12")).getAttribute("value");
      assertThat(value, is("MATRICULAS"));
    }
    {
      String value = driver.findElement(By.name("j_idt7:j_idt13")).getAttribute("value");
      assertThat(value, is("TITULACIONES"));
    }
  }
}
