package es.uma.informatica.sii.trazabilidad.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class SuiteTests {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pruebaInicio() {
    driver.get("http://0.0.0.0:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(891, 749));
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Identificarse"));
    {
      String value = driver.findElement(By.name("j_idt7:j_idt9")).getAttribute("value");
      assertThat(value, is("Alumno/a"));
    }
    {
      String value = driver.findElement(By.name("j_idt7:j_idt11")).getAttribute("value");
      assertThat(value, is("Secretaría"));
    }
  }
}
